################################################################################
# Makefile                                                                     #
#                                                                              #
# Description: This file contains the make rules for Project 1.                #
#                                                                              #
# Author: Yang Sun <yksun@cs.cmu.edu>                                          #
#                                                                              #
################################################################################

all: lisod

lisod:
	@gcc lisod.c -o lisod -Wall -Werror

clean:
	@rm lisod
