all:
	javac */*.java */*/*.java

master:
	java Master.Master Configuration/config.properties

client_1:
	java Client.Client client_1 Configuration/config.properties

client_2:
	java Client.Client client_2 Configuration/config.properties

client_3:
	java Client.Client client_3 Configuration/config.properties

clean:
	rm -rf */*.class */*/*.class
